spring:
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      format_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    datasource:
      hikari:
        maximum-pool-size: 5
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          useLocalSessionState: true
          rewriteBatchedStatements: true
          cacheResultSetMetadata: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false